---
title: "Covid World Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Covid World Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The app is simple to launch.

The app helps users to interact and help explore covid-19 cases in Asia. The app also reflects of other underlying factors that might be contributing to the pandemic indefinitely. 

```{r setup, message=FALSE, warning=FALSE}
library(covidham)
library(tibble)
library(dplyr)

# variables in the data set


glimpse(covid_data)


```


```{r}

# although the app wraps around asian countries, the dataset contains data on the whole world

covid_data %>% filter(continent == "Europe") %>% 
  select(location, 
         date, 
         stringency_index) %>% tibble() 
```



Use the stringency function to get the asian countries stringency index plot. 

```{r,eval=FALSE, echo=TRUE}
stringency()
```

To launch the app use the function 

```{r,eval=FALSE, echo=TRUE}
launch_app()
```


